import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} w-full h-full p-2 bg-gradient-to-r from-sky-500 to-cyan-300 md:overflow-hidden overflow-auto`}
            >
                <NavBar />
                {children}
                <Toaster position="bottom-left"/>
            </body>
        </html>
    );
}
