import Icon01d from "./weather-icons-master/Icon01d.svg";
import Icon01n from "./weather-icons-master/Icon01n.svg";
import Icon02d from "./weather-icons-master/Icon02d.svg";
import Icon02n from "./weather-icons-master/Icon02n.svg";
import Icon03d from "./weather-icons-master/Icon03d.svg";
import Icon03n from "./weather-icons-master/Icon03n.svg";
import Icon04d from "./weather-icons-master/Icon04d.svg";
import Icon04n from "./weather-icons-master/Icon04n.svg";
import Icon09d from "./weather-icons-master/Icon09d.svg";
import Icon09n from "./weather-icons-master/Icon09n.svg";
import Icon10d from "./weather-icons-master/Icon10d.svg";
import Icon10n from "./weather-icons-master/Icon10n.svg";
import Icon11d from "./weather-icons-master/Icon11d.svg";
import Icon11n from "./weather-icons-master/Icon11n.svg";
import Icon13d from "./weather-icons-master/Icon13d.svg";
import Icon13n from "./weather-icons-master/Icon13n.svg";
import Icon50d from "./weather-icons-master/Icon50d.svg";
import Icon50n from "./weather-icons-master/Icon50n.svg";

export const IconMap = new Map<string, any>();
IconMap.set("01d", Icon01d);
IconMap.set("01n", Icon01n);
IconMap.set("02d", Icon02d);
IconMap.set("02n", Icon02n);
IconMap.set("03d", Icon03d);
IconMap.set("03n", Icon03n);
IconMap.set("04d", Icon04d);
IconMap.set("04n", Icon04n);
IconMap.set("09d", Icon09d);
IconMap.set("09n", Icon09n);
IconMap.set("10d", Icon10d);
IconMap.set("10n", Icon10n);
IconMap.set("11d", Icon11d);
IconMap.set("11n", Icon11n);
IconMap.set("13d", Icon13d);
IconMap.set("13n", Icon13n);
IconMap.set("50d", Icon50d);
IconMap.set("50n", Icon50n);
